"""initial schema

Revision ID: f1bf8828eaf3
Revises:
Create Date: 2026-06-18 17:42:31.062944+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f1bf8828eaf3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "superadmin", "admin", "moderator", "support", name="adminrole", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("added_by_admin_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["added_by_admin_id"],
            ["admins.id"],
            name=op.f("fk_admins_added_by_admin_id_admins"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admins")),
    )
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admins_telegram_id"), ["telegram_id"], unique=True)

    op.create_table(
        "faq",
        sa.Column("question", sa.String(length=512), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faq")),
    )
    with op.batch_alter_table("faq", schema=None) as batch_op:
        batch_op.create_index(
            "ix_faq_published_position", ["is_published", "position"], unique=False
        )

    op.create_table(
        "logs",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=False),
        sa.Column("logger", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logs")),
    )
    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.create_index("ix_logs_created_level", ["created_at", "level"], unique=False)

    op.create_table(
        "scheduled_tasks",
        sa.Column(
            "task_type",
            sa.Enum(
                "broadcast",
                "event_publication",
                "event_reminder",
                "registration_close",
                "cleanup",
                name="scheduledtasktype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="scheduledtaskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_tasks")),
        sa.UniqueConstraint("idempotency_key", name="uq_scheduled_tasks_idempotency"),
    )
    with op.batch_alter_table("scheduled_tasks", schema=None) as batch_op:
        batch_op.create_index("ix_scheduled_tasks_due", ["status", "run_at"], unique=False)

    op.create_table(
        "sequence_counters",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_sequence_counters")),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("age_group", sa.String(length=32), nullable=True),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_subscribed", sa.Boolean(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("notifications_consent", sa.Boolean(), nullable=False),
        sa.Column("data_processing_consent", sa.Boolean(), nullable=False),
        sa.Column("registration_completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_age_group", ["age_group"], unique=False)
        batch_op.create_index("ix_users_country", ["country"], unique=False)
        batch_op.create_index("ix_users_is_subscribed", ["is_subscribed"], unique=False)
        batch_op.create_index("ix_users_last_activity_at", ["last_activity_at"], unique=False)
        batch_op.create_index("ix_users_registered_at", ["registered_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_telegram_id"), ["telegram_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=False)

    op.create_table(
        "admin_actions",
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admins.id"],
            name=op.f("fk_admin_actions_admin_id_admins"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_actions")),
    )
    with op.batch_alter_table("admin_actions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_admin_actions_admin_created", ["admin_id", "created_at"], unique=False
        )

    op.create_table(
        "broadcasts",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("parse_mode", sa.String(length=16), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("audience_filter", sa.JSON(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "scheduled",
                "sending",
                "completed",
                "cancelled",
                "failed",
                name="broadcaststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("author_admin_id", sa.String(length=36), nullable=True),
        sa.Column("total_recipients", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("blocked_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_admin_id"],
            ["admins.id"],
            name=op.f("fk_broadcasts_author_admin_id_admins"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcasts")),
    )
    with op.batch_alter_table("broadcasts", schema=None) as batch_op:
        batch_op.create_index("ix_broadcasts_scheduled_at", ["scheduled_at"], unique=False)
        batch_op.create_index("ix_broadcasts_status", ["status"], unique=False)

    op.create_table(
        "events",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_description", sa.String(length=1024), nullable=True),
        sa.Column("full_description", sa.Text(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("address", sa.String(length=512), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("map_url", sa.String(length=2048), nullable=True),
        sa.Column("details_url", sa.String(length=2048), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("registration_enabled", sa.Boolean(), nullable=False),
        sa.Column("registration_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "registration_closed",
                "completed",
                "cancelled",
                "archived",
                name="eventstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("author_admin_id", sa.String(length=36), nullable=True),
        sa.Column("scheduled_publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_admin_id"],
            ["admins.id"],
            name=op.f("fk_events_author_admin_id_admins"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_published_at", ["published_at"], unique=False)
        batch_op.create_index("ix_events_start_at", ["start_at"], unique=False)
        batch_op.create_index("ix_events_status", ["status"], unique=False)

    op.create_table(
        "support_tickets",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "in_progress",
                "waiting_user",
                "resolved",
                "closed",
                name="ticketstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("assigned_admin_id", sa.String(length=36), nullable=True),
        sa.Column("last_reply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_admin_id"],
            ["admins.id"],
            name=op.f("fk_support_tickets_assigned_admin_id_admins"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_support_tickets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_tickets")),
        sa.UniqueConstraint("number", name=op.f("uq_support_tickets_number")),
    )
    with op.batch_alter_table("support_tickets", schema=None) as batch_op:
        batch_op.create_index("ix_support_tickets_status", ["status"], unique=False)
        batch_op.create_index("ix_support_tickets_user", ["user_id"], unique=False)

    op.create_table(
        "user_actions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_actions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_actions")),
    )
    with op.batch_alter_table("user_actions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_actions_user_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "broadcast_buttons",
        sa.Column("broadcast_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("callback_key", sa.String(length=64), nullable=True),
        sa.Column("is_details", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_broadcast_buttons_broadcast_id_broadcasts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_buttons")),
    )
    with op.batch_alter_table("broadcast_buttons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broadcast_buttons_broadcast_id"), ["broadcast_id"], unique=False
        )

    op.create_table(
        "broadcast_files",
        sa.Column("broadcast_id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=512), nullable=False),
        sa.Column("file_unique_id", sa.String(length=512), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum("photo", "document", name="filetype", native_enum=False),
            nullable=False,
        ),
        sa.Column("file_name", sa.String(length=512), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("caption", sa.String(length=1024), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_broadcast_files_broadcast_id_broadcasts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_files")),
    )
    with op.batch_alter_table("broadcast_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broadcast_files_broadcast_id"), ["broadcast_id"], unique=False
        )

    op.create_table(
        "broadcast_recipients",
        sa.Column("broadcast_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "sent",
                "failed",
                "blocked",
                name="recipientstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_broadcast_recipients_broadcast_id_broadcasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_broadcast_recipients_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broadcast_recipients")),
        sa.UniqueConstraint("broadcast_id", "user_id", name="uq_broadcast_recipient"),
    )
    with op.batch_alter_table("broadcast_recipients", schema=None) as batch_op:
        batch_op.create_index(
            "ix_broadcast_recipients_status", ["broadcast_id", "status"], unique=False
        )

    op.create_table(
        "event_files",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=512), nullable=False),
        sa.Column("file_unique_id", sa.String(length=512), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum("photo", "document", name="filetype", native_enum=False),
            nullable=False,
        ),
        sa.Column("file_name", sa.String(length=512), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("caption", sa.String(length=1024), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_files_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_files")),
    )
    with op.batch_alter_table("event_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_files_event_id"), ["event_id"], unique=False)

    op.create_table(
        "event_links",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_details", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_links_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_links")),
    )
    with op.batch_alter_table("event_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_links_event_id"), ["event_id"], unique=False)

    op.create_table(
        "event_reminders",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("minutes_before", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_reminders_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_reminders")),
        sa.UniqueConstraint("event_id", "minutes_before", name="uq_event_reminder_offset"),
    )
    op.create_table(
        "event_views",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_views_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_event_views_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_views")),
    )
    with op.batch_alter_table("event_views", schema=None) as batch_op:
        batch_op.create_index("ix_event_views_event_user", ["event_id", "user_id"], unique=False)
        batch_op.create_index("ix_event_views_viewed_at", ["viewed_at"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("event_id", sa.String(length=36), nullable=True),
        sa.Column("broadcast_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "failed",
                "cancelled",
                name="notificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_notifications_broadcast_id_broadcasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_notifications_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notifications_status_scheduled", ["status", "scheduled_at"], unique=False
        )

    op.create_table(
        "registrations",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "registered",
                "cancelled",
                "attended",
                "absent",
                "waiting_list",
                name="registrationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attended", sa.Boolean(), nullable=True),
        sa.Column("attendance_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_registrations_event_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_registrations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
        sa.UniqueConstraint("user_id", "event_id", name="uq_registrations_user_event"),
    )
    with op.batch_alter_table("registrations", schema=None) as batch_op:
        batch_op.create_index("ix_registrations_status", ["status"], unique=False)
        batch_op.create_index("ix_registrations_user_event", ["user_id", "event_id"], unique=False)

    op.create_table(
        "support_messages",
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column(
            "author_type",
            sa.Enum("user", "admin", "system", name="messageauthortype", native_enum=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("admin_id", sa.String(length=36), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admins.id"],
            name=op.f("fk_support_messages_admin_id_admins"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["support_tickets.id"],
            name=op.f("fk_support_messages_ticket_id_support_tickets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_support_messages_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_messages")),
    )
    with op.batch_alter_table("support_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_support_messages_ticket_id"), ["ticket_id"], unique=False
        )

    op.create_table(
        "support_attachments",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=512), nullable=True),
        sa.Column("file_unique_id", sa.String(length=512), nullable=True),
        sa.Column(
            "file_type",
            sa.Enum("photo", "document", name="filetype", native_enum=False),
            nullable=True,
        ),
        sa.Column("file_name", sa.String(length=512), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("caption", sa.String(length=1024), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["support_messages.id"],
            name=op.f("fk_support_attachments_message_id_support_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_attachments")),
    )
    with op.batch_alter_table("support_attachments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_support_attachments_message_id"), ["message_id"], unique=False
        )

    op.create_table(
        "tracking_links",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("broadcast_id", sa.String(length=36), nullable=True),
        sa.Column("event_id", sa.String(length=36), nullable=True),
        sa.Column("button_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_tracking_links_broadcast_id_broadcasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["button_id"],
            ["broadcast_buttons.id"],
            name=op.f("fk_tracking_links_button_id_broadcast_buttons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_tracking_links_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tracking_links_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_links")),
        sa.UniqueConstraint("token", name="uq_tracking_links_token"),
    )
    with op.batch_alter_table("tracking_links", schema=None) as batch_op:
        batch_op.create_index("ix_tracking_links_broadcast", ["broadcast_id"], unique=False)

    op.create_table(
        "link_clicks",
        sa.Column("tracking_link_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("broadcast_id", sa.String(length=36), nullable=True),
        sa.Column("event_id", sa.String(length=36), nullable=True),
        sa.Column("button_id", sa.String(length=36), nullable=True),
        sa.Column("clicked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["broadcast_id"],
            ["broadcasts.id"],
            name=op.f("fk_link_clicks_broadcast_id_broadcasts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["button_id"],
            ["broadcast_buttons.id"],
            name=op.f("fk_link_clicks_button_id_broadcast_buttons"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_link_clicks_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tracking_link_id"],
            ["tracking_links.id"],
            name=op.f("fk_link_clicks_tracking_link_id_tracking_links"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_link_clicks_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_link_clicks")),
    )
    with op.batch_alter_table("link_clicks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_link_clicks_tracking_clicked", ["tracking_link_id", "clicked_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("link_clicks", schema=None) as batch_op:
        batch_op.drop_index("ix_link_clicks_tracking_clicked")

    op.drop_table("link_clicks")
    with op.batch_alter_table("tracking_links", schema=None) as batch_op:
        batch_op.drop_index("ix_tracking_links_broadcast")

    op.drop_table("tracking_links")
    with op.batch_alter_table("support_attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_support_attachments_message_id"))

    op.drop_table("support_attachments")
    with op.batch_alter_table("support_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_support_messages_ticket_id"))

    op.drop_table("support_messages")
    with op.batch_alter_table("registrations", schema=None) as batch_op:
        batch_op.drop_index("ix_registrations_user_event")
        batch_op.drop_index("ix_registrations_status")

    op.drop_table("registrations")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_status_scheduled")

    op.drop_table("notifications")
    with op.batch_alter_table("event_views", schema=None) as batch_op:
        batch_op.drop_index("ix_event_views_viewed_at")
        batch_op.drop_index("ix_event_views_event_user")

    op.drop_table("event_views")
    op.drop_table("event_reminders")
    with op.batch_alter_table("event_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_links_event_id"))

    op.drop_table("event_links")
    with op.batch_alter_table("event_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_files_event_id"))

    op.drop_table("event_files")
    with op.batch_alter_table("broadcast_recipients", schema=None) as batch_op:
        batch_op.drop_index("ix_broadcast_recipients_status")

    op.drop_table("broadcast_recipients")
    with op.batch_alter_table("broadcast_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broadcast_files_broadcast_id"))

    op.drop_table("broadcast_files")
    with op.batch_alter_table("broadcast_buttons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broadcast_buttons_broadcast_id"))

    op.drop_table("broadcast_buttons")
    with op.batch_alter_table("user_actions", schema=None) as batch_op:
        batch_op.drop_index("ix_user_actions_user_created")

    op.drop_table("user_actions")
    with op.batch_alter_table("support_tickets", schema=None) as batch_op:
        batch_op.drop_index("ix_support_tickets_user")
        batch_op.drop_index("ix_support_tickets_status")

    op.drop_table("support_tickets")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_status")
        batch_op.drop_index("ix_events_start_at")
        batch_op.drop_index("ix_events_published_at")

    op.drop_table("events")
    with op.batch_alter_table("broadcasts", schema=None) as batch_op:
        batch_op.drop_index("ix_broadcasts_status")
        batch_op.drop_index("ix_broadcasts_scheduled_at")

    op.drop_table("broadcasts")
    with op.batch_alter_table("admin_actions", schema=None) as batch_op:
        batch_op.drop_index("ix_admin_actions_admin_created")

    op.drop_table("admin_actions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_telegram_id"))
        batch_op.drop_index("ix_users_registered_at")
        batch_op.drop_index("ix_users_last_activity_at")
        batch_op.drop_index("ix_users_is_subscribed")
        batch_op.drop_index("ix_users_country")
        batch_op.drop_index("ix_users_age_group")

    op.drop_table("users")
    op.drop_table("sequence_counters")
    with op.batch_alter_table("scheduled_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_scheduled_tasks_due")

    op.drop_table("scheduled_tasks")
    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.drop_index("ix_logs_created_level")

    op.drop_table("logs")
    with op.batch_alter_table("faq", schema=None) as batch_op:
        batch_op.drop_index("ix_faq_published_position")

    op.drop_table("faq")
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admins_telegram_id"))

    op.drop_table("admins")
    # ### end Alembic commands ###
